---
- name: Run interfaces role
  hosts: tag_frr
  gather_facts: true
  roles:
    - interfaces
  tags: interfaces

- name: Run frr role
  hosts: tag_frr
  gather_facts: true
  roles:
    - frr
  tags: frr
